export const TYPE_CODES = {
  LOAD_GRANTS: 'LOAD_GRANTS',
  TOGGLE_GRANT: 'TOGGLE_GRANT',
  LOAD_SQL_SCRIPTS: 'LOAD_SQL_SCRIPTS',
  ADD_RANK: 'ADD_RANK',
  DELETE_RANK: 'DELETE_RANK',
  ADD_OPERATION: 'ADD_OPERATION',
  DELETE_OPERATION: 'DELETE_OPERATION',
  TOGGLE_POPUP: 'TOGGLE_POPUP'

}