export const TYPE_CODES = {
  LOAD_GRANTS: 'LOAD_GRANTS',
  TOGGLE_GRANT: 'TOGGLE_GRANT',
  ADD_RANK: 'ADD_RANK',
  DELETE_RANK: 'DELETE_RANK',
  ADD_OPERATION: 'ADD_OPERATION',
  DELETE_OPERATION: 'DELETE_OPERATION',
  SAVE_ATTRIBUTES: 'SAVE_ATTRIBUTES',
  APPLY_OPERATION_CODE_FILTER: 'APPLY_OPERATION_CODE_FILTER'
}